sudo: required
language: python
services:
- docker
python:
- '3.6'
before_script:
- docker-compose build
script:
- docker-compose run --rm web bash -c "flake8 . && python wait_for_postgres.py &&
  ./manage.py test"
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
  registry.heroku.com; docker tag web registry.heroku.com/gamaron-api-prod/web; docker
  push registry.heroku.com/gamaron-api-prod/web; fi
- if [ "$TRAVIS_BRANCH" == "qa" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
  registry.heroku.com; docker tag web registry.heroku.com/gamaron-api-qa/web; docker
  push registry.heroku.com/gamaron-api-qa/web; fi
notifications:
  email: false
cache:
  pip: true
env:
  global:
  - secure: WPMdSjRaZCT6IpwDScFXrLVrZMDDC2PYXt1eL07guuQGJVw8d5Wg7+bxJq728S+QZtL0Xd1TikgtfCxH0uiSDcSMf2525CsS21Jo8dQ3Km9vokM3ISUWygmScKj93ioeFcGupVjarm+Zhk9UTuPMus9aQ4eIgDxUHffb1fu7f3pV/XZmMDHtUWtNtcKzGntSoI81Chpcnas51ye/5kY3hKbJwJyvuScr0AciuGOUiGa6G80DI7gA0DKC6GA6EcuYFFRI4i2PSPtMeeG59jYeJoa+Wszh9S9Oy8IigvYyOc6jQBDpoFH2PP2i07+ztrEYVSPamIEUbTeZ8xCIg9GUpuxe5jOtPkqmAh5m9/73ofmbVSz7lW2GJuXeGqJ4fEPSJq/A3XVEAXwOPKzDZA2OPzuAUqHxzEdsFH9E1/VXcLIoZkY83Gu8yiDZHDlxd9ktSlI3c/8taQBEmc8d8FdBBSXNqRs9XqVFsqiIVqsFnPBxGXfaaVnYIZ1p5beoI6kxxl/hOptzSDLl8ns66bYeJjVnu9MHONQbJISQnQYV6B1bApY7snYz53j9JhpgN/PazG1vfS2YbTwc+Xb4SNt17GqU9aRnWNJ9FSniWkspmjqRLk9Zqc1S1Rd3J2NSAt80LL2R9V5OKLXLc//hJfgg3oTN1pBaE64lV4CzGE1DMZY=
  - secure: qu/E2pdpG9YkJV7O6Nd7jklBIMhHdSIRcysWH96oIe14UbBcaE4QhUXbgXokFPvzn24ouhYAl1Jufjq0782QuIquTZRXjChN5kdEz5a7phKGaGraF+jWkRxHEmOvpE0vdUdILwPS5ydIP3HAqVsbUafVkrt+n+rMEDMBHpQuX6fVkcykCXKGeK4nPvoidpbs86dtW4EwLSse2qIArQ9wKExw97hsKbOXZjLKxgqv4XX18gztT+ajAhkB8iZ4gNMcXsInaaepFpJnZJIBhYuUceoJXYglJV8IbuqPl/+e1jrQEZiozA5DIS+tYK7cZ5bXX+FP4d4Ww/lGntBUp81oYo2rJ5L+Xc3EVK7oKaXfnbLR/qQ0DZ1rgp5ADs9DTMFfAUT2iE2jP7UyZR03EZM4TBdgUlMzHFpOtLIWikN9uwDAMULHYNn7dKk26v7A+YBUDtttV7eeuW9CHr8ERCnCU+uufMilGx3sayN0pPne49jU0r0m9gl0uYlJtH+xHj+c1a8tfLIAqfGfCbnbcBaEWUH3U5rPBkMBpHZuWz7eudaRqbBSfe1erV+5IWEdNKvBS34O56skgiLVSNDU9qTTuzFKQ2JUaG0E/JnGrigngLMyLWkPzAxkJ2lj5yloGIBQH8b5BYWbmHjy+rTqoXMFr6OeacLSnI9bHsy6gHMIB0s=
  - secure: l56pbRqcIWOYt/I0zNN0JBwXz2V3QaReVFdEiecriIH7iEyDdDPrxdLDt95WPMnD3BnOovqCdYgc8B0+JuQSEFUe1FJ5eAMN0gcdJcZSnFip21Aw/Tdh9blDCZvQNUxJAZ6bdDgKGSb57wVbjvvzfuWvYfMsmlHZU22KaLQLAOrkf/b5cfF5NqAliGY2e69dIx/mikHYtOo7JLCOg9FrCSV3nVyd/o8twfsddc2Q1hYzZ3g1vMfY/ToutSZ4hDKIsr1FE57Q0nsOoi/x/mmvlQWPtmHTezJRvzNqK+sc3iGmM1apkBOPz/KxZ2iaUjXYqrQeO7fJY5QPGgkq0TFecHk7P6FUrFO5I4QfdCUyDgst+PSw9f70NA4b9HHGYeKqOYv5mb459BgrvZRXvMONL9l1k14DmE6t9d1LimUX0vHFwPYA8b3Wsd1Ag97XogHS3DXx3D7t31+voVTRJERqJtasCtInh43Ux8h7qRVpM5MVM/70f7zb7xk3EWgduymvkVZU+35+0YwPeu+ZL1p3JFBxMCUqAKVMmednNkqpRiTGKdBtlkocNZ/xj2Qk04VBPjKIzq1I8aA113hAgBMS14B9S+t1CqeSwRrjcqbNA6NkL6JBfssf0bAVZ3T+zj0bzTNQ1P8xCiNnKrevDd7GjUf44jw6lXPA8coUJA5lHgM=
